# Generated by Django 3.0.6 on 2020-05-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200505_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwithprice',
            name='sub_subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sub_SubCategory'),
        ),
    ]
