# Generated by Django 3.0.6 on 2020-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_pic_2',
            field=models.ImageField(null=True, upload_to='product_picture/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pic_3',
            field=models.ImageField(null=True, upload_to='product_picture/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pic_4',
            field=models.ImageField(null=True, upload_to='product_picture/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(null=True, upload_to='product_picture/'),
        ),
    ]
