# Generated by Django 3.0.6 on 2020-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200506_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, null=True, upload_to='product_picture/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_2',
            field=models.ImageField(blank=True, null=True, upload_to='product_picture/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_3',
            field=models.ImageField(blank=True, null=True, upload_to='product_picture/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic_4',
            field=models.ImageField(blank=True, null=True, upload_to='product_picture/'),
        ),
    ]
