# Generated by Django 3.0.6 on 2020-05-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200506_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwithprice',
            name='affiliate_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
