# Generated by Django 3.0.6 on 2020-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productwithprice_affiliate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sub_subcategory',
            field=models.ManyToManyField(to='main.Sub_SubCategory'),
        ),
    ]
